FROM python:3.10-slim

WORKDIR /app

COPY requirements-api.txt .

RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r requirements-api.txt

COPY app/ app/
COPY src/ src/
COPY models/ models/

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]