FROM python:3.10-slim

WORKDIR /app

COPY requirements-streamlit.txt .

RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r requirements-streamlit.txt

COPY dashboard/ dashboard/

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "dashboard/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]